#pragma once
#include "../ast/ast_nodes.h"
#include <sstream>
#include <string>
#include <stdexcept>
#include <map>
#include <set>
#include <vector>

class CppGenerator {
public:
    std::string generate(const ProgramNode& program) {
        std::ostringstream out;
        out << "// ==========================================\n";
        out << "// Generated by TagLang Compiler v3.0\n";
        out << "// ==========================================\n";
        out << "#include <iostream>\n";
        out << "#include <string>\n";
        out << "#include <vector>\n";
        out << "#include <cmath>\n";
        out << "#include <iomanip>\n";
        out << "#include <map>\n\n";
        out << "int main() {\n";
        for (const auto& node : program.blocks)
            genNode(out, *node, 1);
        out << "\n    return 0;\n}\n";
        return out.str();
    }

private:
    std::set<std::string>     declaredVars;
    std::map<std::string,int> varConflicts;

    std::string indent(int level) { return std::string(level * 4, ' '); }

    std::string safeName(const std::string& name) {
        if (declaredVars.find(name) == declaredVars.end()) {
            declaredVars.insert(name);
            return name;
        }
        int& cnt = varConflicts[name];
        cnt++;
        std::string safe = name + "_" + std::to_string(cnt + 1);
        declaredVars.insert(safe);
        return safe;
    }

    std::string escStr(const std::string& s) {
        std::string r;
        for (char c : s) { if (c=='"') r+="\\\""; else if (c=='\\') r+="\\\\"; else r+=c; }
        return r;
    }

    void genNode(std::ostringstream& out, const ASTNode& node, int lvl) {
        const std::string& k = node.kind();
        if      (k=="DataBlock")    genDataBlock   (out, static_cast<const DataBlockNode&>   (node), lvl);
        else if (k=="CalcBlock")    genCalcBlock   (out, static_cast<const CalcBlockNode&>   (node), lvl);
        else if (k=="LogicBlock")   genLogicBlock  (out, static_cast<const LogicBlockNode&>  (node), lvl);
        else if (k=="OutBlock")     genOutBlock    (out, static_cast<const OutBlockNode&>    (node), lvl);
        else if (k=="FlowBlock")    genFlowBlock   (out, static_cast<const FlowBlockNode&>   (node), lvl);
        else if (k=="RScriptBlock") genRScriptBlock(out, static_cast<const RScriptBlockNode&>(node), lvl);
        else if (k=="JsonBlock")    genJsonBlock   (out, static_cast<const JsonBlockNode&>   (node), lvl);
        else if (k=="PtrBlock")     genPtrBlock    (out, static_cast<const PtrBlockNode&>    (node), lvl);
        else if (k=="ErrorBlock")   genErrorBlock  (out, static_cast<const ErrorBlockNode&>  (node), lvl);
        else if (k=="CArrayBlock")  genArrayBlock  (out, static_cast<const CArrayBlockNode&> (node), lvl);
        else if (k=="LambdaBlock")  genLambdaBlock (out, static_cast<const LambdaBlockNode&> (node), lvl);
        else if (k=="IterBlock")    genIterBlock   (out, static_cast<const IterBlockNode&>   (node), lvl);
        else if (k=="ObjBlock")     genObjBlock    (out, static_cast<const ObjBlockNode&>    (node), lvl);
        else if (k=="FuncBlock")    genFuncBlock   (out, static_cast<const FuncBlockNode&>   (node), lvl);
        else throw std::runtime_error("Unknown node kind: " + k);
    }

    // ── @data ──────────────────────────────────────────────
    void genDataBlock(std::ostringstream& out, const DataBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @data ---\n";
        for (const auto& e : b.entries) {
            declaredVars.insert(e->name);
            out << indent(lvl);
            if (e->dataType=="string")
                out << "std::string " << e->name << " = \"" << e->value << "\";\n";
            else if (e->dataType=="int")
                out << "int " << e->name << " = " << e->value << ";\n";
            else if (e->dataType=="float")
                out << "double " << e->name << " = " << e->value << ";\n";
            else if (e->dataType=="bool")
                out << "bool " << e->name << " = " << e->value << ";\n";
            else if (e->dataType=="array") {
                std::string et="int"; bool isStr=false;
                if (!e->arrayItems.empty()) {
                    const std::string& f=e->arrayItems[0];
                    if (f.size()>4&&f.substr(0,4)=="STR:") { et="std::string"; isStr=true; }
                    else if (f.find('.')!=std::string::npos) et="double";
                }
                out << "std::vector<" << et << "> " << e->name << " = {";
                for (int i=0; i<(int)e->arrayItems.size(); i++) {
                    if (i) out << ", ";
                    std::string item=e->arrayItems[i];
                    if (isStr&&item.size()>4&&item.substr(0,4)=="STR:")
                        out << "\"" << item.substr(4) << "\"";
                    else out << item;
                }
                out << "};\n";
            }
        }
    }

    // ── @calc ──────────────────────────────────────────────
    void genCalcBlock(std::ostringstream& out, const CalcBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @calc ---\n";
        for (const auto& e : b.exprs) {
            declaredVars.insert(e->lhs);
            out << indent(lvl) << "auto " << e->lhs << " = " << e->expr << ";\n";
        }
    }

    // ── @logic ─────────────────────────────────────────────
    void genLogicBlock(std::ostringstream& out, const LogicBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @logic ---\n";
        for (const auto& s : b.statements) genLogicStmt(out, *s, lvl);
    }

    void genLogicStmt(std::ostringstream& out, const ASTNode& node, int lvl) {
        const std::string& k = node.kind();
        if (k=="Print") {
            const auto& n = static_cast<const PrintNode&>(node);
            out << indent(lvl) << "std::cout << " << n.expr->raw << " << std::endl;\n";
        } else if (k=="Assign") {
            const auto& n = static_cast<const AssignNode&>(node);
            if (declaredVars.find(n.varName)==declaredVars.end()) {
                out << indent(lvl) << "auto " << n.varName << " = " << n.value->raw << ";\n";
                declaredVars.insert(n.varName);
            } else {
                out << indent(lvl) << n.varName << " = " << n.value->raw << ";\n";
            }
        } else if (k=="If") {
            const auto& n = static_cast<const IfNode&>(node);
            out << indent(lvl) << "if (" << n.condition->raw << ") {\n";
            for (const auto& s : n.thenBody) genLogicStmt(out, *s, lvl+1);
            out << indent(lvl) << "}";
            if (!n.elseBody.empty()) {
                out << " else {\n";
                for (const auto& s : n.elseBody) genLogicStmt(out, *s, lvl+1);
                out << indent(lvl) << "}";
            }
            out << "\n";
        } else if (k=="While") {
            const auto& n = static_cast<const WhileNode&>(node);
            out << indent(lvl) << "while (" << n.condition->raw << ") {\n";
            for (const auto& s : n.body) genLogicStmt(out, *s, lvl+1);
            out << indent(lvl) << "}\n";
        } else if (k=="Repeat") {
            const auto& n = static_cast<const RepeatNode&>(node);
            out << indent(lvl) << "for (int _i=0; _i<" << n.times << "; _i++) {\n";
            for (const auto& s : n.body) genLogicStmt(out, *s, lvl+1);
            out << indent(lvl) << "}\n";
        } else {
            throw std::runtime_error("Unknown logic stmt: " + k);
        }
    }

    // ── @out ───────────────────────────────────────────────
    void genOutBlock(std::ostringstream& out, const OutBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @out ---\n";
        for (const auto& line : b.lines) {
            std::string tmpl = line->tmpl;
            std::vector<std::pair<bool,std::string>> parts;
            std::string seg;
            for (int i=0; i<(int)tmpl.size(); ) {
                if (tmpl[i]=='{') {
                    if (!seg.empty()) { parts.push_back({false,seg}); seg.clear(); }
                    int j=i+1;
                    while (j<(int)tmpl.size()&&tmpl[j]!='}') j++;
                    parts.push_back({true, tmpl.substr(i+1, j-i-1)});
                    i=j+1;
                } else seg+=tmpl[i++];
            }
            if (!seg.empty()) parts.push_back({false,seg});
            out << indent(lvl) << "std::cout";
            for (const auto& p : parts)
                out << (p.first ? " << " + p.second : " << \"" + escStr(p.second) + "\"");
            if (parts.empty()) out << " << \"\"";
            out << " << std::endl;\n";
        }
    }

    // ── @flow ──────────────────────────────────────────────
    void genFlowBlock(std::ostringstream& out, const FlowBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @flow ---\n";
        out << indent(lvl) << "// Flow:\n";
        for (const auto& s : b.steps) {
            out << indent(lvl) << "//   " << s->from << " -> " << s->to;
            if (!s->condition.empty()) out << "  (if " << s->condition << ")";
            out << "\n";
        }
        std::map<std::string,std::vector<const FlowStepNode*>> byFrom;
        std::vector<std::string> labels;
        std::set<std::string> allLabels;
        for (const auto& s : b.steps) {
            if (byFrom.find(s->from)==byFrom.end()) labels.push_back(s->from);
            byFrom[s->from].push_back(s.get());
            allLabels.insert(s->from); allLabels.insert(s->to);
        }
        out << indent(lvl) << "goto flow_" << b.entry << ";\n";
        for (const auto& lbl : labels) {
            out << indent(lvl) << "flow_" << lbl << ":\n";
            const auto& steps = byFrom[lbl];
            if (steps.size()==1 && steps[0]->condition.empty())
                out << indent(lvl+1) << "goto flow_" << steps[0]->to << ";\n";
            else
                for (const auto* s : steps)
                    out << indent(lvl+1)
                        << (s->condition.empty() ? "" : "if ("+s->condition+") ")
                        << "goto flow_" << s->to << ";\n";
        }
        for (const auto& lbl : allLabels)
            if (byFrom.find(lbl)==byFrom.end())
                out << indent(lvl) << "flow_" << lbl << ": ;\n";
    }

    // ── @rscript (FIX 3) ───────────────────────────────────
    void genRScriptBlock(std::ostringstream& out, const RScriptBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @rscript (R Language) ---\n";
        for (const auto& s : b.stmts) {
            const std::string& k = s->kind();
            if (k=="RAssign") {
                const auto& n = static_cast<const RAssignNode&>(*s);
                std::string sn = safeName(n.lhs);
                out << indent(lvl) << "auto " << sn << " = " << n.rhs << ";\n";
            } else if (k=="RVec") {
                const auto& n = static_cast<const RVecNode&>(*s);
                std::string et="int";
                if (!n.elements.empty()&&n.elements[0].find('"')!=std::string::npos) et="std::string";
                else if (!n.elements.empty()&&n.elements[0].find('.')!=std::string::npos) et="double";
                std::string sn = safeName(n.name);
                out << indent(lvl) << "std::vector<" << et << "> " << sn << " = {";
                for (int i=0; i<(int)n.elements.size(); i++) { if(i) out<<", "; out<<n.elements[i]; }
                out << "};\n";
                // FIX 3: create _str version usable in @out
                std::string strNm = sn + "_str";
                if (declaredVars.find(strNm)==declaredVars.end()) {
                    declaredVars.insert(strNm);
                    out << indent(lvl) << "std::string " << strNm << " = \"c(\";\n";
                    out << indent(lvl) << "for (size_t _vi=0; _vi<" << sn << ".size(); _vi++) {\n";
                    out << indent(lvl+1) << "if (_vi) " << strNm << " += \", \";\n";
                    out << indent(lvl+1) << strNm << " += std::to_string(" << sn << "[_vi]);\n";
                    out << indent(lvl) << "}\n";
                    out << indent(lvl) << strNm << " += \")\";\n";
                }
            } else if (k=="RPrint") {
                const auto& n = static_cast<const RPrintNode&>(*s);
                bool isVec = false;
                for (const auto& s2 : b.stmts)
                    if (s2->kind()=="RVec" && static_cast<const RVecNode&>(*s2).name==n.expr)
                        { isVec=true; break; }
                if (isVec) {
                    out << indent(lvl) << "std::cout << \"c(\";\n";
                    out << indent(lvl) << "for (size_t _vi=0; _vi<" << n.expr << ".size(); _vi++) {\n";
                    out << indent(lvl+1) << "if (_vi) std::cout << \", \";\n";
                    out << indent(lvl+1) << "std::cout << " << n.expr << "[_vi];\n";
                    out << indent(lvl) << "}\n";
                    out << indent(lvl) << "std::cout << \")\\n\" << std::endl;\n";
                } else {
                    out << indent(lvl) << "std::cout << " << n.expr << " << std::endl;\n";
                }
            }
        }
    }

    // ── @json ──────────────────────────────────────────────
    void genJsonBlock(std::ostringstream& out, const JsonBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @json (JavaScript JSON) ---\n";
        for (const auto& s : b.stmts) {
            const std::string& k = s->kind();
            if (k=="JsonObj") {
                const auto& obj = static_cast<const JsonObjNode&>(*s);
                out << indent(lvl) << "// object: " << obj.name << "\n";
                for (const auto& f : obj.fields) {
                    std::string vn = obj.name+"_"+f->key;
                    declaredVars.insert(vn);
                    out << indent(lvl);
                    if (f->valueType=="string")      out<<"std::string "<<vn<<" = \""<<f->value<<"\";\n";
                    else if (f->valueType=="int")    out<<"int "<<vn<<" = "<<f->value<<";\n";
                    else if (f->valueType=="float")  out<<"double "<<vn<<" = "<<f->value<<";\n";
                    else if (f->valueType=="bool")   out<<"bool "<<vn<<" = "<<f->value<<";\n";
                }
            } else if (k=="JsonStringify") {
                const auto& n = static_cast<const JsonStringifyNode&>(*s);
                declaredVars.insert(n.varName);
                out << indent(lvl) << "std::string " << n.varName << " = \"{\";\n";
                for (const auto& s2 : b.stmts) {
                    if (s2->kind()!="JsonObj") continue;
                    const auto& obj = static_cast<const JsonObjNode&>(*s2);
                    if (obj.name!=n.objName) continue;
                    for (int i=0; i<(int)obj.fields.size(); i++) {
                        const auto& f = obj.fields[i];
                        std::string vn = obj.name+"_"+f->key;
                        out << indent(lvl) << n.varName << " += \"\\\"" << f->key << "\\\": \";\n";
                        if (f->valueType=="string")
                            out << indent(lvl) << n.varName << " += \"\\\"\" + " << vn << " + \"\\\"\";\n";
                        else
                            out << indent(lvl) << n.varName << " += std::to_string(" << vn << ");\n";
                        if (i<(int)obj.fields.size()-1)
                            out << indent(lvl) << n.varName << " += \", \";\n";
                    }
                }
                out << indent(lvl) << n.varName << " += \"}\";\n";
            } else if (k=="JsonParse") {
                const auto& n = static_cast<const JsonParseNode&>(*s);
                out << indent(lvl) << "std::string " << n.varName << "_raw = " << n.jsonStr << ";\n";
                declaredVars.insert(n.varName+"_raw");
            } else if (k=="ErrorPrint") {
                const auto& n = static_cast<const ErrorPrintNode&>(*s);
                std::string expr = n.expr;
                for (char& c : expr) if (c=='.') c='_';
                out << indent(lvl) << "std::cout << " << expr << " << std::endl;\n";
            }
        }
    }

    // ── @ptr ───────────────────────────────────────────────
    void genPtrBlock(std::ostringstream& out, const PtrBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @ptr (GoLang/C Pointers) ---\n";
        for (const auto& s : b.stmts) genPtrStmt(out, *s, lvl);
    }
    void genPtrStmt(std::ostringstream& out, const ASTNode& s, int lvl) {
        const std::string& k = s.kind();
        if (k=="PtrVarDecl") {
            const auto& n = static_cast<const PtrVarDeclNode&>(s);
            std::string ct=(n.type=="float")?"double":n.type;
            declaredVars.insert(n.name);
            out << indent(lvl) << ct << " " << n.name << " = " << n.value << ";\n";
        } else if (k=="PtrDecl") {
            const auto& n = static_cast<const PtrDeclNode&>(s);
            std::string ct=(n.type=="float")?"double":n.type;
            declaredVars.insert(n.name);
            out << indent(lvl) << ct << "* " << n.name << " = nullptr;\n";
        } else if (k=="PtrAssignAddr") {
            const auto& n = static_cast<const PtrAssignAddrNode&>(s);
            out << indent(lvl) << n.ptrName << " = &" << n.varName << ";\n";
        } else if (k=="PtrDerefAssign") {
            const auto& n = static_cast<const PtrDerefAssignNode&>(s);
            out << indent(lvl) << "*" << n.ptrName << " = " << n.value << ";\n";
        } else if (k=="PtrPrint") {
            const auto& n = static_cast<const PtrPrintNode&>(s);
            out << indent(lvl) << "std::cout << " << n.expr << " << std::endl;\n";
        } else if (k=="PtrFunc") {
            const auto& n = static_cast<const PtrFuncNode&>(s);
            std::string ct=(n.paramType=="float")?"double":n.paramType;
            declaredVars.insert(n.funcName);
            out << indent(lvl) << "auto " << n.funcName << " = [&](" << ct << "* " << n.paramName << ") {\n";
            for (const auto& stmt : n.body) genPtrStmt(out, *stmt, lvl+1);
            out << indent(lvl) << "};\n";
        } else if (k=="PtrCall") {
            const auto& n = static_cast<const PtrCallNode&>(s);
            out << indent(lvl) << n.funcName << "(" << n.arg << ");\n";
        }
    }

    // ── @error ─────────────────────────────────────────────
    void genErrorBlock(std::ostringstream& out, const ErrorBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @error (Java Exceptions) ---\n";
        for (const auto& s : b.stmts) genErrorStmt(out, *s, lvl);
    }
    void genErrorStmt(std::ostringstream& out, const ASTNode& s, int lvl) {
        const std::string& k = s.kind();
        if (k=="TryCatch") {
            const auto& n = static_cast<const TryCatchNode&>(s);
            out << indent(lvl) << "try {\n";
            for (const auto& stmt : n.tryBody) genErrorStmt(out, *stmt, lvl+1);
            out << indent(lvl) << "}";
            if (!n.catchBody.empty()) {
                out << " catch (std::exception& " << n.exceptionVar << ") {\n";
                for (const auto& stmt : n.catchBody) genErrorStmt(out, *stmt, lvl+1);
                out << indent(lvl) << "}";
            }
            if (!n.finallyBody.empty()) {
                out << "\n" << indent(lvl) << "// finally:\n" << indent(lvl) << "{\n";
                for (const auto& stmt : n.finallyBody) genErrorStmt(out, *stmt, lvl+1);
                out << indent(lvl) << "}";
            }
            out << "\n";
        } else if (k=="Throw") {
            const auto& n = static_cast<const ThrowNode&>(s);
            out << indent(lvl) << "throw std::runtime_error(\"" << n.message << "\");\n";
        } else if (k=="ErrorPrint") {
            const auto& n = static_cast<const ErrorPrintNode&>(s);
            std::string expr=n.expr;
            bool isVar=!expr.empty()&&expr[0]!='"'&&expr.find(' ')==std::string::npos&&expr.find('"')==std::string::npos;
            out << indent(lvl) << "std::cout << " << expr << (isVar?".what()":"") << " << std::endl;\n";
        }
    }

    // ── @array ─────────────────────────────────────────────
    void genArrayBlock(std::ostringstream& out, const CArrayBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @array (C Arrays) ---\n";
        for (const auto& s : b.stmts) {
            const std::string& k = s->kind();
            if (k=="CArrayDecl") {
                const auto& n = static_cast<const CArrayDeclNode&>(*s);
                int sz=n.size>0?n.size:(int)n.elements.size();
                declaredVars.insert(n.name);
                out << indent(lvl) << n.elemType << " " << n.name << "[" << sz << "] = {";
                for (int i=0; i<(int)n.elements.size(); i++) { if(i) out<<", "; out<<n.elements[i]; }
                out << "};\n";
            } else if (k=="CCharStr") {
                const auto& n = static_cast<const CCharStrNode&>(*s);
                declaredVars.insert(n.name);
                out << indent(lvl);
                if (n.isPtr) out<<"const char* "<<n.name<<" = \""<<n.value<<"\";\n";
                else         out<<"char "<<n.name<<"[] = \""<<n.value<<"\";\n";
            } else if (k=="CArrayPrint") {
                const auto& n = static_cast<const CArrayPrintNode&>(*s);
                if (!n.index.empty())
                    out<<indent(lvl)<<"std::cout << "<<n.name<<"["<<n.index<<"] << std::endl;\n";
                else
                    out<<indent(lvl)<<"std::cout << "<<n.name<<" << std::endl;\n";
            }
        }
    }

    // ── @lambda ────────────────────────────────────────────
    void genLambdaBlock(std::ostringstream& out, const LambdaBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @lambda (C# Lambda) ---\n";
        for (const auto& s : b.stmts) {
            const std::string& k = s->kind();
            if (k=="LambdaDecl") {
                const auto& n = static_cast<const LambdaDeclNode&>(*s);
                declaredVars.insert(n.name);
                out << indent(lvl) << "auto " << n.name << " = [](";
                for (int i=0; i<(int)n.params.size(); i++) { if(i) out<<", "; out<<"auto "<<n.params[i]; }
                out << ") { return " << n.body << "; };\n";
            } else if (k=="LambdaCall") {
                const auto& n = static_cast<const LambdaCallNode&>(*s);
                std::string call=n.lambdaName+"(";
                for (int i=0; i<(int)n.args.size(); i++) { if(i) call+=", "; call+=n.args[i]; }
                call+=")";
                if (!n.resultVar.empty()) {
                    if (declaredVars.find(n.resultVar)==declaredVars.end()) {
                        out<<indent(lvl)<<"auto "<<n.resultVar<<" = "<<call<<";\n";
                        declaredVars.insert(n.resultVar);
                    } else out<<indent(lvl)<<n.resultVar<<" = "<<call<<";\n";
                } else out<<indent(lvl)<<"std::cout << "<<call<<" << std::endl;\n";
            } else if (k=="LambdaPrint") {
                const auto& n = static_cast<const LambdaPrintNode&>(*s);
                out<<indent(lvl)<<"std::cout << "<<n.expr<<" << std::endl;\n";
            }
        }
    }

    // ── @iter (FIX 1: Assign support) ─────────────────────
    void genIterBlock(std::ostringstream& out, const IterBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @iter (Rust Iteration) ---\n";
        for (const auto& s : b.stmts) genIterStmt(out, *s, lvl);
    }
    void genIterStmt(std::ostringstream& out, const ASTNode& s, int lvl) {
        const std::string& k = s.kind();
        if (k=="ForRange") {
            const auto& n = static_cast<const ForRangeNode&>(s);
            if (!n.label.empty()) out<<indent(lvl)<<n.label<<":\n";
            out<<indent(lvl)<<"for (auto "<<n.var<<" = "<<n.from
               <<"; "<<n.var<<(n.inclusive?" <= ":" < ")<<n.to
               <<"; ++"<<n.var<<") {\n";
            for (const auto& stmt : n.body) genIterStmt(out,*stmt,lvl+1);
            out<<indent(lvl)<<"}\n";
        } else if (k=="ForIn") {
            const auto& n = static_cast<const ForInNode&>(s);
            if (!n.label.empty()) out<<indent(lvl)<<n.label<<":\n";
            out<<indent(lvl)<<"for (const auto& "<<n.var<<" : "<<n.collection<<") {\n";
            for (const auto& stmt : n.body) genIterStmt(out,*stmt,lvl+1);
            out<<indent(lvl)<<"}\n";
        } else if (k=="Loop") {
            const auto& n = static_cast<const LoopNode&>(s);
            if (!n.label.empty()) out<<indent(lvl)<<n.label<<":\n";
            out<<indent(lvl)<<"while (true) {\n";
            for (const auto& stmt : n.body) genIterStmt(out,*stmt,lvl+1);
            out<<indent(lvl)<<"}\n";
        } else if (k=="IterWhile") {
            const auto& n = static_cast<const IterWhileNode&>(s);
            out<<indent(lvl)<<"while ("<<n.condition<<") {\n";
            for (const auto& stmt : n.body) genIterStmt(out,*stmt,lvl+1);
            out<<indent(lvl)<<"}\n";
        } else if (k=="Break") {
            out<<indent(lvl)<<"break;\n";
        } else if (k=="IterPrint") {
            const auto& n = static_cast<const IterPrintNode&>(s);
            out<<indent(lvl)<<"std::cout << "<<n.expr<<" << std::endl;\n";
        } else if (k=="Assign") {
            // FIX 1: @iter now supports x = expr (new or existing var)
            const auto& n = static_cast<const AssignNode&>(s);
            if (declaredVars.find(n.varName)==declaredVars.end()) {
                out<<indent(lvl)<<"auto "<<n.varName<<" = "<<n.value->raw<<";\n";
                declaredVars.insert(n.varName);
            } else {
                out<<indent(lvl)<<n.varName<<" = "<<n.value->raw<<";\n";
            }
        }
    }

    // ── @obj (FIX 2: print_row) ────────────────────────────
    void genObjBlock(std::ostringstream& out, const ObjBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @obj (Ruby/Lua Objects) ---\n";
        for (const auto& s : b.stmts) {
            const std::string& k = s->kind();
            if (k=="ObjTable") {
                const auto& n = static_cast<const ObjTableNode&>(*s);
                declaredVars.insert(n.name);
                if (n.fields.empty()) {
                    out<<indent(lvl)<<"std::map<std::string,std::string> "<<n.name<<";\n";
                } else if (n.fields[0].first.empty()) {
                    out<<indent(lvl)<<"std::vector<int> "<<n.name<<" = {";
                    for (int i=0; i<(int)n.fields.size(); i++) { if(i) out<<", "; out<<n.fields[i].second; }
                    out<<"}\n;";
                } else {
                    out<<indent(lvl)<<"std::map<std::string,std::string> "<<n.name<<" = {\n";
                    for (const auto& f : n.fields) {
                        std::string v=(f.second[0]=='"')?f.second:"std::to_string("+f.second+")";
                        out<<indent(lvl+1)<<"{\""<<f.first<<"\", "<<v<<"},\n";
                    }
                    out<<indent(lvl)<<"};\n";
                }
            } else if (k=="ObjSetField") {
                const auto& n = static_cast<const ObjSetFieldNode&>(*s);
                if (n.field.empty()) continue;
                out<<indent(lvl)<<n.objName<<"[\""<<n.field<<"\"] = "
                   <<(n.value[0]=='"'?n.value:"std::to_string("+n.value+")")<<";\n";
            } else if (k=="ObjQuery") {
                const auto& n = static_cast<const ObjQueryNode&>(*s);
                declaredVars.insert(n.varName);
                if (n.method=="respond_to")
                    out<<indent(lvl)<<"bool "<<n.varName<<" = ("<<n.objName<<".find(\""<<n.arg
                       <<"\") != "<<n.objName<<".end());\n";
                else if (n.method=="is_a")
                    out<<indent(lvl)<<"bool "<<n.varName<<" = true; // is_a: "<<n.arg<<"\n";
                else if (n.method=="nil")
                    out<<indent(lvl)<<"bool "<<n.varName<<" = "<<n.objName<<".empty();\n";
                else
                    out<<indent(lvl)<<"auto "<<n.varName<<" = "<<n.objName<<"[\""<<n.arg<<"\"];\n";
            } else if (k=="ObjPrintRow") {
                // FIX 2: print all fields on ONE line
                const auto& n = static_cast<const ObjPrintRowNode&>(*s);
                bool found=false;
                for (const auto& s2 : b.stmts) {
                    if (s2->kind()!="ObjTable") continue;
                    const auto& obj=static_cast<const ObjTableNode&>(*s2);
                    if (obj.name!=n.objName) continue;
                    found=true;
                    out<<indent(lvl)<<"std::cout << \"| \"";
                    for (const auto& f : obj.fields)
                        if (!f.first.empty())
                            out<<" << "<<n.objName<<"[\""<<f.first<<"\"] << \" | \"";
                    out<<" << std::endl;\n";
                }
                if (!found) {
                    out<<indent(lvl)<<"for (const auto& _kv : "<<n.objName
                       <<") std::cout << \"| \" << _kv.second << \" \";\n";
                    out<<indent(lvl)<<"std::cout << std::endl;\n";
                }
            } else if (k=="ObjPrint") {
                const auto& n = static_cast<const ObjPrintNode&>(*s);
                std::string expr=n.expr;
                auto dot=expr.find('.');
                if (dot!=std::string::npos && expr.find('[')==std::string::npos) {
                    out<<indent(lvl)<<"std::cout << "<<expr.substr(0,dot)<<"[\""<<expr.substr(dot+1)<<"\"] << std::endl;\n";
                } else if (expr.find('[')!=std::string::npos) {
                    auto b2=expr.find('['), e2=expr.find(']');
                    int idx=0; try { idx=std::stoi(expr.substr(b2+1,e2-b2-1))-1; } catch(...) {}
                    out<<indent(lvl)<<"std::cout << "<<expr.substr(0,b2)<<"["<<idx<<"] << std::endl;\n";
                } else {
                    out<<indent(lvl)<<"std::cout << "<<expr<<" << std::endl;\n";
                }
            }
        }
    }

    // ── @func (FIX 4) ──────────────────────────────────────
    void genFuncBlock(std::ostringstream& out, const FuncBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @func (TagLang Functions) ---\n";
        // Pass 1: emit lambda definitions
        for (const auto& s : b.stmts) {
            if (s->kind()!="FuncDef") continue;
            const auto& fn = static_cast<const FuncDefNode&>(*s);
            declaredVars.insert(fn.name);
            out<<indent(lvl)<<"auto "<<fn.name<<" = [&](";
            for (int i=0; i<(int)fn.params.size(); i++) { if(i) out<<", "; out<<"auto "<<fn.params[i]; }
            out<<") {\n";
            for (const auto& stmt : fn.body) {
                if (stmt->kind()=="FuncAssign") {
                    const auto& a=static_cast<const FuncAssignNode&>(*stmt);
                    if (declaredVars.find(a.varName)==declaredVars.end())
                        out<<indent(lvl+1)<<"auto "<<a.varName<<" = "<<a.value<<";\n";
                    else
                        out<<indent(lvl+1)<<a.varName<<" = "<<a.value<<";\n";
                }
            }
            if (!fn.retExpr.empty()) out<<indent(lvl+1)<<"return "<<fn.retExpr<<";\n";
            out<<indent(lvl)<<"};\n";
        }
        // Pass 2: calls, assignments, prints
        for (const auto& s : b.stmts) {
            const std::string& k=s->kind();
            if (k=="FuncDef") continue;
            if (k=="FuncCallStmt") {
                const auto& n=static_cast<const FuncCallStmtNode&>(*s);
                std::string call=n.funcName+"(";
                for (int i=0; i<(int)n.args.size(); i++) { if(i) call+=", "; call+=n.args[i]; }
                call+=")";
                if (!n.resultVar.empty()) {
                    if (declaredVars.find(n.resultVar)==declaredVars.end()) {
                        out<<indent(lvl)<<"auto "<<n.resultVar<<" = "<<call<<";\n";
                        declaredVars.insert(n.resultVar);
                    } else out<<indent(lvl)<<n.resultVar<<" = "<<call<<";\n";
                } else out<<indent(lvl)<<"std::cout << "<<call<<" << std::endl;\n";
            } else if (k=="FuncPrint") {
                const auto& n=static_cast<const FuncPrintNode&>(*s);
                out<<indent(lvl)<<"std::cout << "<<n.expr<<" << std::endl;\n";
            } else if (k=="FuncAssign") {
                const auto& n=static_cast<const FuncAssignNode&>(*s);
                if (declaredVars.find(n.varName)==declaredVars.end()) {
                    out<<indent(lvl)<<"auto "<<n.varName<<" = "<<n.value<<";\n";
                    declaredVars.insert(n.varName);
                } else out<<indent(lvl)<<n.varName<<" = "<<n.value<<";\n";
            }
        }
    }
};
