#pragma once
#include "../ast/ast_nodes.h"
#include <sstream>
#include <string>
#include <stdexcept>
#include <map>
#include <set>
#include <vector>

// ============================================================
//  CppGenerator — duyệt AST và sinh C++ source code
// ============================================================
class CppGenerator {
public:
    std::string generate(const ProgramNode& program) {
        std::ostringstream out;

        // Header
        out << "// ============================================\n";
        out << "// Generated by TagLang Compiler\n";
        out << "// ============================================\n";
        out << "#include <iostream>\n";
        out << "#include <string>\n";
        out << "#include <vector>\n";
        out << "#include <cmath>\n";
        out << "#include <iomanip>\n";
        out << "#include <map>\n\n";
        out << "int main() {\n";

        for (const auto& node : program.blocks) {
            genNode(out, *node, 1);
        }

        out << "\n    return 0;\n";
        out << "}\n";
        return out.str();
    }

private:
    std::set<std::string> declaredVars; // track vars for @logic assign

    std::string indent(int level) {
        return std::string(level * 4, ' ');
    }

    void genNode(std::ostringstream& out, const ASTNode& node, int lvl) {
        const std::string& k = node.kind();
        if      (k == "DataBlock")     genDataBlock(out,    static_cast<const DataBlockNode&>(node),    lvl);
        else if (k == "CalcBlock")     genCalcBlock(out,    static_cast<const CalcBlockNode&>(node),    lvl);
        else if (k == "LogicBlock")    genLogicBlock(out,   static_cast<const LogicBlockNode&>(node),   lvl);
        else if (k == "OutBlock")      genOutBlock(out,     static_cast<const OutBlockNode&>(node),     lvl);
        else if (k == "FlowBlock")     genFlowBlock(out,    static_cast<const FlowBlockNode&>(node),    lvl);
        else if (k == "RScriptBlock")  genRScriptBlock(out, static_cast<const RScriptBlockNode&>(node), lvl);
        else if (k == "JsonBlock")     genJsonBlock(out,    static_cast<const JsonBlockNode&>(node),    lvl);
        else if (k == "PtrBlock")      genPtrBlock(out,     static_cast<const PtrBlockNode&>(node),     lvl);
        else if (k == "ErrorBlock")    genErrorBlock(out,   static_cast<const ErrorBlockNode&>(node),   lvl);
        else if (k == "CArrayBlock")   genArrayBlock(out,   static_cast<const CArrayBlockNode&>(node),  lvl);
        else if (k == "LambdaBlock")   genLambdaBlock(out,  static_cast<const LambdaBlockNode&>(node),  lvl);
        else if (k == "IterBlock")     genIterBlock(out,    static_cast<const IterBlockNode&>(node),    lvl);
        else if (k == "ObjBlock")      genObjBlock(out,     static_cast<const ObjBlockNode&>(node),     lvl);
        else throw std::runtime_error("Unknown node kind: " + k);
    }

    // ----------------------------------------------------------
    //  @data
    // ----------------------------------------------------------
    void genDataBlock(std::ostringstream& out, const DataBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @data ---\n";
        for (const auto& e : b.entries) {
            declaredVars.insert(e->name);
            out << indent(lvl);
            if (e->dataType == "string") {
                out << "std::string " << e->name << " = \"" << e->value << "\";\n";
            } else if (e->dataType == "int") {
                out << "int " << e->name << " = " << e->value << ";\n";
            } else if (e->dataType == "float") {
                out << "double " << e->name << " = " << e->value << ";\n";
            } else if (e->dataType == "bool") {
                out << "bool " << e->name << " = " << e->value << ";\n";
            } else if (e->dataType == "array") {
                // Đoán kiểu từ phần tử đầu tiên
                std::string elemType = "int";
                bool isStrArray = false;
                if (!e->arrayItems.empty()) {
                    const std::string& first = e->arrayItems[0];
                    if (first.find('.') != std::string::npos) elemType = "double";
                    // items tagged with STR: prefix by data_parser
                    if (first.size() > 4 && first.substr(0,4) == "STR:") {
                        elemType = "std::string"; isStrArray = true;
                    }
                }
                out << "std::vector<" << elemType << "> " << e->name << " = {";
                for (int i = 0; i < (int)e->arrayItems.size(); i++) {
                    if (i) out << ", ";
                    std::string item = e->arrayItems[i];
                    if (isStrArray && item.size() > 4 && item.substr(0,4) == "STR:")
                        out << "\"" << item.substr(4) << "\"";
                    else
                        out << item;
                }
                out << "};\n";
            }
        }
    }

    // ----------------------------------------------------------
    //  @calc
    // ----------------------------------------------------------
    void genCalcBlock(std::ostringstream& out, const CalcBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @calc ---\n";
        for (const auto& e : b.exprs) {
            declaredVars.insert(e->lhs);
            // Dùng auto để tự suy kiểu
            out << indent(lvl) << "auto " << e->lhs
                << " = " << e->expr << ";\n";
        }
    }

    // ----------------------------------------------------------
    //  @logic
    // ----------------------------------------------------------
    void genLogicBlock(std::ostringstream& out, const LogicBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @logic ---\n";
        for (const auto& stmt : b.statements) {
            genLogicStmt(out, *stmt, lvl);
        }
    }

    void genLogicStmt(std::ostringstream& out, const ASTNode& node, int lvl) {
        const std::string& k = node.kind();

        if (k == "Print") {
            const auto& p = static_cast<const PrintNode&>(node);
            out << indent(lvl) << "std::cout << " << p.expr->raw << " << std::endl;\n";
        }
        else if (k == "Assign") {
            const auto& a = static_cast<const AssignNode&>(node);
            if (declaredVars.find(a.varName) == declaredVars.end()) {
                out << indent(lvl) << "auto " << a.varName << " = " << a.value->raw << ";\n";
                declaredVars.insert(a.varName);
            } else {
                out << indent(lvl) << a.varName << " = " << a.value->raw << ";\n";
            }
        }
        else if (k == "If") {
            const auto& ifn = static_cast<const IfNode&>(node);
            out << indent(lvl) << "if (" << ifn.condition->raw << ") {\n";
            for (const auto& s : ifn.thenBody) genLogicStmt(out, *s, lvl+1);
            out << indent(lvl) << "}";
            if (!ifn.elseBody.empty()) {
                out << " else {\n";
                for (const auto& s : ifn.elseBody) genLogicStmt(out, *s, lvl+1);
                out << indent(lvl) << "}";
            }
            out << "\n";
        }
        else if (k == "While") {
            const auto& wn = static_cast<const WhileNode&>(node);
            out << indent(lvl) << "while (" << wn.condition->raw << ") {\n";
            for (const auto& s : wn.body) genLogicStmt(out, *s, lvl+1);
            out << indent(lvl) << "}\n";
        }
        else if (k == "Repeat") {
            const auto& rn = static_cast<const RepeatNode&>(node);
            out << indent(lvl) << "for (int _i = 0; _i < " << rn.times << "; _i++) {\n";
            for (const auto& s : rn.body) genLogicStmt(out, *s, lvl+1);
            out << indent(lvl) << "}\n";
        }
        else {
            throw std::runtime_error("Unknown logic statement: " + k);
        }
    }

    // ----------------------------------------------------------
    //  @out — template string {var} → biến
    // ----------------------------------------------------------
    void genOutBlock(std::ostringstream& out, const OutBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @out ---\n";
        for (const auto& line : b.lines) {
            std::string tmpl = line->tmpl;
            // Build list of parts: {isVar, content}
            std::vector<std::pair<bool,std::string>> parts;
            std::string seg;
            for (int i = 0; i < (int)tmpl.size(); ) {
                if (tmpl[i] == '{') {
                    if (!seg.empty()) { parts.push_back({false, seg}); seg.clear(); }
                    int j = i + 1;
                    while (j < (int)tmpl.size() && tmpl[j] != '}') j++;
                    parts.push_back({true, tmpl.substr(i+1, j-i-1)});
                    i = j + 1;
                } else {
                    seg += tmpl[i++];
                }
            }
            if (!seg.empty()) parts.push_back({false, seg});
            // Emit: std::cout << part1 << part2 << std::endl;
            out << indent(lvl) << "std::cout";
            for (const auto& p : parts) {
                if (p.first) out << " << " << p.second;
                else         out << " << \"" << escapeStr(p.second) << "\"";
            }
            if (parts.empty()) out << " << \"\"";
            out << " << std::endl;\n";
        }
    }

    std::string escapeStr(const std::string& s) {
        std::string r;
        for (char c : s) {
            if (c == '"')  r += "\\\"";
            else if (c == '\\') r += "\\\\";
            else r += c;
        }
        return r;
    }

    // ----------------------------------------------------------
    //  @flow — sinh comment diagram + goto-based C++
    // ----------------------------------------------------------
    void genFlowBlock(std::ostringstream& out, const FlowBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @flow ---\n";
        out << indent(lvl) << "// Flow diagram:\n";
        for (const auto& s : b.steps) {
            out << indent(lvl) << "//   " << s->from << " -> " << s->to;
            if (!s->condition.empty()) out << "  (if " << s->condition << ")";
            out << "\n";
        }
        out << indent(lvl) << "// (Flow execution represented as labeled blocks)\n";

        // Gom các step theo "from" label
        std::vector<std::string> labels;
        std::map<std::string, std::vector<const FlowStepNode*>> byFrom;
        for (const auto& s : b.steps) {
            if (byFrom.find(s->from) == byFrom.end())
                labels.push_back(s->from);
            byFrom[s->from].push_back(s.get());
        }

        // Collect all label names (from AND to)
        std::set<std::string> allLabels;
        for (const auto& s : b.steps) { allLabels.insert(s->from); allLabels.insert(s->to); }

        // Emit goto-based blocks
        out << indent(lvl) << "goto flow_" << b.entry << ";\n";
        for (const auto& lbl : labels) {
            out << indent(lvl) << "flow_" << lbl << ":\n";
            const auto& steps = byFrom[lbl];
            if (steps.size() == 1 && steps[0]->condition.empty()) {
                out << indent(lvl+1) << "goto flow_" << steps[0]->to << ";\n";
            } else {
                for (const auto* step : steps) {
                    if (!step->condition.empty()) {
                        out << indent(lvl+1) << "if (" << step->condition << ") "
                            << "goto flow_" << step->to << ";\n";
                    } else {
                        out << indent(lvl+1) << "goto flow_" << step->to << ";\n";
                    }
                }
            }
        }
        // Emit terminal labels (appear as "to" but not "from")
        for (const auto& lbl : allLabels) {
            if (byFrom.find(lbl) == byFrom.end()) {
                out << indent(lvl) << "flow_" << lbl << ": ;\n";
            }
        }
    }
    // ==========================================================
    //  @rscript — R language style
    // ==========================================================
    void genRScriptBlock(std::ostringstream& out, const RScriptBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @rscript (R Language) ---\n";
        for (const auto& s : b.stmts) {
            const std::string& k = s->kind();
            if (k == "RAssign") {
                const auto& n = static_cast<const RAssignNode&>(*s);
                declaredVars.insert(n.lhs);
                // If rhs looks like a string value, wrap in quotes
                std::string rhsVal = n.rhs;
                if (!rhsVal.empty() && rhsVal[0] != '"' && !isdigit(rhsVal[0]) &&
                    rhsVal != "true" && rhsVal != "false") {
                    // It was a string literal whose quotes were stripped -- re-add them
                    // Actually rhs from parser is already raw value; strings stored as content
                    // RAssignNode rhs = raw collected tokens; if it was STRING token, value is without quotes
                    // We need to check: if the collected rhs has no operators and is pure alpha -> it's a var ref
                    // The parser stores the raw token value for strings (no quotes)
                    // We detect: if rhs has spaces or is purely alpha with no known variable -> string
                }
                out << indent(lvl) << "auto " << n.lhs << " = " << rhsVal << ";\n";
            } else if (k == "RVec") {
                const auto& n = static_cast<const RVecNode&>(*s);
                declaredVars.insert(n.name);
                // Detect type from first element
                std::string elemType = "int";
                if (!n.elements.empty() && n.elements[0].find('"') != std::string::npos)
                    elemType = "std::string";
                else if (!n.elements.empty() && n.elements[0].find('.') != std::string::npos)
                    elemType = "double";
                out << indent(lvl) << "std::vector<" << elemType << "> " << n.name << " = {";
                for (int i=0; i<(int)n.elements.size(); i++) {
                    if (i) out << ", ";
                    out << n.elements[i];
                }
                out << "};\n";
            } else if (k == "RPrint") {
                const auto& n = static_cast<const RPrintNode&>(*s);
                // Check if expr is a vector variable - if so, print element by element
                // We detect by checking if it was declared as a vector (RVec)
                bool isVec = false;
                for (const auto& s2 : b.stmts) {
                    if (s2->kind() == "RVec") {
                        const auto& v = static_cast<const RVecNode&>(*s2);
                        if (v.name == n.expr) { isVec = true; break; }
                    }
                }
                if (isVec) {
                    out << indent(lvl) << "std::cout << \"c(\";\n";
                    out << indent(lvl) << "for (size_t _vi=0; _vi<" << n.expr << ".size(); _vi++) {\n";
                    out << indent(lvl+1) << "if (_vi) std::cout << \", \";\n";
                    out << indent(lvl+1) << "std::cout << " << n.expr << "[_vi];\n";
                    out << indent(lvl) << "}\n";
                    out << indent(lvl) << "std::cout << \")\\n\" << std::endl;\n";
                } else {
                    out << indent(lvl) << "std::cout << " << n.expr << " << std::endl;\n";
                }
            }
        }
    }
    // ==========================================================
    //  @json — JavaScript JSON style
    // ==========================================================
    void genJsonBlock(std::ostringstream& out, const JsonBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @json (JavaScript JSON) ---\n";
        // Collect all object names for struct generation
        std::vector<std::string> structNames;
        for (const auto& s : b.stmts) {
            if (s->kind() == "JsonObj") {
                const auto& obj = static_cast<const JsonObjNode&>(*s);
                structNames.push_back(obj.name);
            }
        }
        for (const auto& s : b.stmts) {
            const std::string& k = s->kind();
            if (k == "JsonObj") {
                const auto& obj = static_cast<const JsonObjNode&>(*s);
                // Emit as struct instance (simplified)
                out << indent(lvl) << "// object: " << obj.name << "\n";
                for (const auto& f : obj.fields) {
                    std::string varName = obj.name + "_" + f->key;
                    declaredVars.insert(varName);
                    if (f->valueType == "string")
                        out << indent(lvl) << "std::string " << varName << " = \"" << f->value << "\";\n";
                    else if (f->valueType == "int")
                        out << indent(lvl) << "int " << varName << " = " << f->value << ";\n";
                    else if (f->valueType == "float")
                        out << indent(lvl) << "double " << varName << " = " << f->value << ";\n";
                    else if (f->valueType == "bool")
                        out << indent(lvl) << "bool " << varName << " = " << f->value << ";\n";
                }
            } else if (k == "JsonStringify") {
                const auto& n = static_cast<const JsonStringifyNode&>(*s);
                // Emit a JSON-like string by concatenating fields
                out << indent(lvl) << "std::string " << n.varName << " = \"{\";\n";
                // Find the object
                for (const auto& s2 : b.stmts) {
                    if (s2->kind() == "JsonObj") {
                        const auto& obj = static_cast<const JsonObjNode&>(*s2);
                        if (obj.name == n.objName) {
                            for (int i=0; i<(int)obj.fields.size(); i++) {
                                const auto& f = obj.fields[i];
                                out << indent(lvl) << n.varName << " += \"\\\"" << f->key << "\\\": \";\n";
                                std::string varName = obj.name + "_" + f->key;
                                if (f->valueType == "string")
                                    out << indent(lvl) << n.varName << " += \"\\\"\" + " << varName << " + \"\\\"\";\n";
                                else
                                    out << indent(lvl) << n.varName << " += std::to_string(" << varName << ");\n";
                                if (i < (int)obj.fields.size()-1)
                                    out << indent(lvl) << n.varName << " += \", \";\n";
                            }
                        }
                    }
                }
                out << indent(lvl) << n.varName << " += \"}\";\n";
                declaredVars.insert(n.varName);
            } else if (k == "JsonParse") {
                const auto& n = static_cast<const JsonParseNode&>(*s);
                out << indent(lvl) << "// JSON.parse -> " << n.varName << " (parsed from " << n.jsonStr << ")\n";
                out << indent(lvl) << "std::string " << n.varName << "_raw = " << n.jsonStr << ";\n";
                declaredVars.insert(n.varName + "_raw");
            } else if (k == "ErrorPrint") {
                const auto& n = static_cast<const ErrorPrintNode&>(*s);
                // Handle obj.field notation
                std::string expr = n.expr;
                // Replace . with _ for struct field access simulation
                for (char& c : expr) if (c == '.') c = '_';
                out << indent(lvl) << "std::cout << " << expr << " << std::endl;\n";
            }
        }
    }
    // ==========================================================
    //  @ptr — Go/C pointer style
    // ==========================================================
    void genPtrBlock(std::ostringstream& out, const PtrBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @ptr (GoLang/C Pointers) ---\n";
        for (const auto& s : b.stmts) genPtrStmt(out, *s, lvl);
    }
    void genPtrStmt(std::ostringstream& out, const ASTNode& s, int lvl) {
        const std::string& k = s.kind();
        if (k == "PtrVarDecl") {
            const auto& n = static_cast<const PtrVarDeclNode&>(s);
            std::string ctype = n.type == "int" ? "int" : n.type == "float" ? "double" : n.type;
            declaredVars.insert(n.name);
            out << indent(lvl) << ctype << " " << n.name << " = " << n.value << ";\n";
        } else if (k == "PtrDecl") {
            const auto& n = static_cast<const PtrDeclNode&>(s);
            std::string ctype = n.type == "int" ? "int" : "double";
            declaredVars.insert(n.name);
            out << indent(lvl) << ctype << "* " << n.name << " = nullptr;\n";
        } else if (k == "PtrAssignAddr") {
            const auto& n = static_cast<const PtrAssignAddrNode&>(s);
            out << indent(lvl) << n.ptrName << " = &" << n.varName << ";\n";
        } else if (k == "PtrDerefAssign") {
            const auto& n = static_cast<const PtrDerefAssignNode&>(s);
            // If name is a pointer, dereference
            out << indent(lvl) << "*" << n.ptrName << " = " << n.value << ";\n";
        } else if (k == "PtrPrint") {
            const auto& n = static_cast<const PtrPrintNode&>(s);
            out << indent(lvl) << "std::cout << " << n.expr << " << std::endl;\n";
        } else if (k == "PtrFunc") {
            const auto& n = static_cast<const PtrFuncNode&>(s);
            std::string ctype = n.paramType == "int" ? "int" : "double";
            out << indent(lvl) << "auto " << n.funcName << " = [&](" << ctype << "* "
                << n.paramName << ") {\n";
            for (const auto& stmt : n.body) genPtrStmt(out, *stmt, lvl+1);
            out << indent(lvl) << "};\n";
            declaredVars.insert(n.funcName);
        } else if (k == "PtrCall") {
            const auto& n = static_cast<const PtrCallNode&>(s);
            out << indent(lvl) << n.funcName << "(" << n.arg << ");\n";
        }
    }
    // ==========================================================
    //  @error — Java exception style
    // ==========================================================
    void genErrorBlock(std::ostringstream& out, const ErrorBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @error (Java Exceptions) ---\n";
        for (const auto& s : b.stmts) genErrorStmt(out, *s, lvl);
    }
    void genErrorStmt(std::ostringstream& out, const ASTNode& s, int lvl) {
        const std::string& k = s.kind();
        if (k == "TryCatch") {
            const auto& n = static_cast<const TryCatchNode&>(s);
            out << indent(lvl) << "try {\n";
            for (const auto& stmt : n.tryBody) genErrorStmt(out, *stmt, lvl+1);
            out << indent(lvl) << "}";
            if (!n.catchBody.empty()) {
                out << " catch (std::exception& " << n.exceptionVar << ") {\n";
                for (const auto& stmt : n.catchBody) genErrorStmt(out, *stmt, lvl+1);
                out << indent(lvl) << "}";
            }
            if (!n.finallyBody.empty()) {
                // C++ has no finally — use RAII simulation comment
                out << "\n" << indent(lvl) << "// finally:\n" << indent(lvl) << "{\n";
                for (const auto& stmt : n.finallyBody) genErrorStmt(out, *stmt, lvl+1);
                out << indent(lvl) << "}";
            }
            out << "\n";
        } else if (k == "Throw") {
            const auto& n = static_cast<const ThrowNode&>(s);
            out << indent(lvl) << "throw std::runtime_error(\"" << n.message << "\");\n";
        } else if (k == "ErrorPrint") {
            const auto& n = static_cast<const ErrorPrintNode&>(s);
            std::string expr = n.expr;
            // Only call .what() if expr is a bare identifier (the exception variable)
            // not if it's a string literal (starts with ")
            bool isExceptionVar = !expr.empty() && expr[0] != '"' &&
                                  expr.find(' ') == std::string::npos &&
                                  expr.find('"') == std::string::npos;
            if (isExceptionVar) {
                out << indent(lvl) << "std::cout << " << expr << ".what() << std::endl;\n";
            } else {
                out << indent(lvl) << "std::cout << " << expr << " << std::endl;\n";
            }
        }
    }
    // ==========================================================
    //  @array — C array style
    // ==========================================================
    void genArrayBlock(std::ostringstream& out, const CArrayBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @array (C Arrays) ---\n";
        for (const auto& s : b.stmts) {
            const std::string& k = s->kind();
            if (k == "CArrayDecl") {
                const auto& n = static_cast<const CArrayDeclNode&>(*s);
                int sz = n.size > 0 ? n.size : (int)n.elements.size();
                out << indent(lvl) << n.elemType << " " << n.name << "[" << sz << "] = {";
                for (int i=0; i<(int)n.elements.size(); i++) {
                    if (i) out << ", ";
                    out << n.elements[i];
                }
                out << "};\n";
                declaredVars.insert(n.name);
            } else if (k == "CCharStr") {
                const auto& n = static_cast<const CCharStrNode&>(*s);
                if (n.isPtr)
                    out << indent(lvl) << "const char* " << n.name << " = \"" << n.value << "\";\n";
                else
                    out << indent(lvl) << "char " << n.name << "[] = \"" << n.value << "\";\n";
                declaredVars.insert(n.name);
            } else if (k == "CArrayPrint") {
                const auto& n = static_cast<const CArrayPrintNode&>(*s);
                if (!n.index.empty())
                    out << indent(lvl) << "std::cout << " << n.name << "[" << n.index << "] << std::endl;\n";
                else
                    out << indent(lvl) << "std::cout << " << n.name << " << std::endl;\n";
            }
        }
    }
    // ==========================================================
    //  @lambda — C# lambda style
    // ==========================================================
    void genLambdaBlock(std::ostringstream& out, const LambdaBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @lambda (C# Lambda) ---\n";
        for (const auto& s : b.stmts) {
            const std::string& k = s->kind();
            if (k == "LambdaDecl") {
                const auto& n = static_cast<const LambdaDeclNode&>(*s);
                out << indent(lvl) << "auto " << n.name << " = [](";
                for (int i=0; i<(int)n.params.size(); i++) {
                    if (i) out << ", ";
                    out << "auto " << n.params[i];
                }
                out << ") { return " << n.body << "; };\n";
                declaredVars.insert(n.name);
            } else if (k == "LambdaCall") {
                const auto& n = static_cast<const LambdaCallNode&>(*s);
                std::string call = n.lambdaName + "(";
                for (int i=0; i<(int)n.args.size(); i++) {
                    if (i) call += ", ";
                    call += n.args[i];
                }
                call += ")";
                if (!n.resultVar.empty()) {
                    if (declaredVars.find(n.resultVar) == declaredVars.end()) {
                        out << indent(lvl) << "auto " << n.resultVar << " = " << call << ";\n";
                        declaredVars.insert(n.resultVar);
                    } else {
                        out << indent(lvl) << n.resultVar << " = " << call << ";\n";
                    }
                } else {
                    out << indent(lvl) << "std::cout << " << call << " << std::endl;\n";
                }
            } else if (k == "LambdaPrint") {
                const auto& n = static_cast<const LambdaPrintNode&>(*s);
                out << indent(lvl) << "std::cout << " << n.expr << " << std::endl;\n";
            }
        }
    }
    // ==========================================================
    //  @iter — Rust iteration style
    // ==========================================================
    void genIterBlock(std::ostringstream& out, const IterBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @iter (Rust Iteration) ---\n";
        for (const auto& s : b.stmts) genIterStmt(out, *s, lvl);
    }
    void genIterStmt(std::ostringstream& out, const ASTNode& s, int lvl) {
        const std::string& k = s.kind();
        if (k == "ForRange") {
            const auto& n = static_cast<const ForRangeNode&>(s);
            if (!n.label.empty()) out << indent(lvl) << n.label << ":\n";
            std::string cmp = n.inclusive ? "<=" : "<";
            out << indent(lvl) << "for (auto " << n.var << " = " << n.from
                << "; " << n.var << " " << cmp << " " << n.to
                << "; ++" << n.var << ") {\n";
            for (const auto& stmt : n.body) genIterStmt(out, *stmt, lvl+1);
            out << indent(lvl) << "}\n";
        } else if (k == "ForIn") {
            const auto& n = static_cast<const ForInNode&>(s);
            if (!n.label.empty()) out << indent(lvl) << n.label << ":\n";
            out << indent(lvl) << "for (const auto& " << n.var
                << " : " << n.collection << ") {\n";
            for (const auto& stmt : n.body) genIterStmt(out, *stmt, lvl+1);
            out << indent(lvl) << "}\n";
        } else if (k == "Loop") {
            const auto& n = static_cast<const LoopNode&>(s);
            if (!n.label.empty()) out << indent(lvl) << n.label << ":\n";
            out << indent(lvl) << "while (true) {\n";
            for (const auto& stmt : n.body) genIterStmt(out, *stmt, lvl+1);
            out << indent(lvl) << "}\n";
        } else if (k == "IterWhile") {
            const auto& n = static_cast<const IterWhileNode&>(s);
            out << indent(lvl) << "while (" << n.condition << ") {\n";
            for (const auto& stmt : n.body) genIterStmt(out, *stmt, lvl+1);
            out << indent(lvl) << "}\n";
        } else if (k == "Break") {
            const auto& n = static_cast<const BreakNode&>(s);
            out << indent(lvl) << "break;\n";
            (void)n;
        } else if (k == "IterPrint") {
            const auto& n = static_cast<const IterPrintNode&>(s);
            out << indent(lvl) << "std::cout << " << n.expr << " << std::endl;\n";
        }
    }
    // ==========================================================
    //  @obj — Ruby/Lua object/table style
    // ==========================================================
    void genObjBlock(std::ostringstream& out, const ObjBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @obj (Ruby/Lua Objects) ---\n";
        // First pass: collect table definitions for context
        for (const auto& s : b.stmts) {
            const std::string& k = s->kind();
            if (k == "ObjTable") {
                const auto& n = static_cast<const ObjTableNode&>(*s);
                if (n.fields.empty()) {
                    out << indent(lvl) << "// " << n.name << " = {} (empty table)\n";
                    out << indent(lvl) << "std::map<std::string, std::string> " << n.name << ";\n";
                    declaredVars.insert(n.name);
                } else {
                    bool isArray = n.fields[0].first.empty();
                    if (isArray) {
                        out << indent(lvl) << "std::vector<int> " << n.name << " = {";
                        for (int i=0; i<(int)n.fields.size(); i++) {
                            if (i) out << ", ";
                            out << n.fields[i].second;
                        }
                        out << "};\n";
                    } else {
                        out << indent(lvl) << "std::map<std::string, std::string> " << n.name << " = {\n";
                        for (const auto& f : n.fields) {
                            out << indent(lvl+1) << "{\"" << f.first << "\", "
                                << (f.second[0]=='"' ? f.second : "std::to_string("+f.second+")")
                                << "},\n";
                        }
                        out << indent(lvl) << "};\n";
                    }
                    declaredVars.insert(n.name);
                }
            } else if (k == "ObjSetField") {
                const auto& n = static_cast<const ObjSetFieldNode&>(*s);
                if (n.field.empty()) continue; // skip plain assign
                // Map insert / update
                out << indent(lvl) << n.objName << "[\"" << n.field << "\"] = "
                    << (n.value[0]=='"' ? n.value : "std::to_string("+n.value+")") << ";\n";
            } else if (k == "ObjQuery") {
                const auto& n = static_cast<const ObjQueryNode&>(*s);
                if (n.method == "respond_to") {
                    out << indent(lvl) << "bool " << n.varName << " = ("
                        << n.objName << ".find(\"" << n.arg << "\") != "
                        << n.objName << ".end());\n";
                } else if (n.method == "is_a") {
                    out << indent(lvl) << "bool " << n.varName
                        << " = true; // is_a check: " << n.objName << " is " << n.arg << "\n";
                } else if (n.method == "nil") {
                    out << indent(lvl) << "bool " << n.varName << " = "
                        << n.objName << ".empty();\n";
                } else {
                    out << indent(lvl) << "auto " << n.varName << " = "
                        << n.objName << "[\"" << n.arg << "\"];\n";
                }
                declaredVars.insert(n.varName);
            } else if (k == "ObjPrint") {
                const auto& n = static_cast<const ObjPrintNode&>(*s);
                // Handle t.field -> t["field"]
                std::string expr = n.expr;
                // Check for dot notation: obj.field
                auto dot = expr.find('.');
                if (dot != std::string::npos) {
                    std::string obj = expr.substr(0, dot);
                    std::string field = expr.substr(dot+1);
                    // Check if it's array indexing: arr[0]
                    auto bracket = expr.find('[');
                    if (bracket != std::string::npos) {
                        out << indent(lvl) << "std::cout << " << expr << " << std::endl;\n";
                    } else {
                        out << indent(lvl) << "std::cout << " << obj
                            << "[\"" << field << "\"] << std::endl;\n";
                    }
                } else if (expr.find('[') != std::string::npos) {
                    // arr[1] -> arr[0] (Lua 1-indexed -> C++ 0-indexed)
                    auto b2 = expr.find('[');
                    auto e2 = expr.find(']');
                    std::string arrName = expr.substr(0, b2);
                    std::string idx = expr.substr(b2+1, e2-b2-1);
                    int idxVal = 0;
                    try { idxVal = std::stoi(idx) - 1; } catch (...) { idxVal = 0; }
                    out << indent(lvl) << "std::cout << " << arrName
                        << "[" << idxVal << "] << std::endl;\n";
                } else {
                    out << indent(lvl) << "std::cout << " << expr << " << std::endl;\n";
                }
            }
        }
    }
};
