#pragma once
#include "../ast/ast_nodes.h"
#include <sstream>
#include <string>
#include <stdexcept>
#include <map>
#include <set>
#include <vector>

class CppGenerator {
public:
    std::string generate(const ProgramNode& program) {
        std::ostringstream out;

        out << "// ============================================\n";
        out << "// Generated by TagLang Compiler\n";
        out << "// ============================================\n";
        out << "#include <iostream>\n";
        out << "#include <string>\n";
        out << "#include <vector>\n";
        out << "#include <cmath>\n";
        out << "#include <iomanip>\n\n";
        out << "int main() {\n";

        for (const auto& node : program.blocks) {
            genNode(out, *node, 1);
        }

        out << "\n    return 0;\n";
        out << "}\n";
        return out.str();
    }

private:
    std::set<std::string> declaredVars; 

    std::string indent(int level) {
        return std::string(level * 4, ' ');
    }

    void genNode(std::ostringstream& out, const ASTNode& node, int lvl) {
        const std::string& k = node.kind();
        if      (k == "DataBlock")  genDataBlock(out,  static_cast<const DataBlockNode&>(node),  lvl);
        else if (k == "CalcBlock")  genCalcBlock(out,  static_cast<const CalcBlockNode&>(node),  lvl);
        else if (k == "LogicBlock") genLogicBlock(out, static_cast<const LogicBlockNode&>(node), lvl);
        else if (k == "OutBlock")   genOutBlock(out,   static_cast<const OutBlockNode&>(node),   lvl);
        else if (k == "FlowBlock")  genFlowBlock(out,  static_cast<const FlowBlockNode&>(node),  lvl);
        else throw std::runtime_error("Unknown node kind: " + k);
    }

    void genDataBlock(std::ostringstream& out, const DataBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @data ---\n";
        for (const auto& e : b.entries) {
            declaredVars.insert(e->name);
            out << indent(lvl);
            if (e->dataType == "string") {
                out << "std::string " << e->name << " = \"" << e->value << "\";\n";
            } else if (e->dataType == "int") {
                out << "int " << e->name << " = " << e->value << ";\n";
            } else if (e->dataType == "float") {
                out << "double " << e->name << " = " << e->value << ";\n";
            } else if (e->dataType == "bool") {
                out << "bool " << e->name << " = " << e->value << ";\n";
            } else if (e->dataType == "array") {
                std::string elemType = "int";
                bool isStrArray = false;
                if (!e->arrayItems.empty()) {
                    const std::string& first = e->arrayItems[0];
                    if (first.find('.') != std::string::npos) elemType = "double";
                    if (first.size() > 4 && first.substr(0,4) == "STR:") {
                        elemType = "std::string"; isStrArray = true;
                    }
                }
                out << "std::vector<" << elemType << "> " << e->name << " = {";
                for (int i = 0; i < (int)e->arrayItems.size(); i++) {
                    if (i) out << ", ";
                    std::string item = e->arrayItems[i];
                    if (isStrArray && item.size() > 4 && item.substr(0,4) == "STR:")
                        out << "\"" << item.substr(4) << "\"";
                    else
                        out << item;
                }
                out << "};\n";
            }
        }
    }

    void genCalcBlock(std::ostringstream& out, const CalcBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @calc ---\n";
        for (const auto& e : b.exprs) {
            declaredVars.insert(e->lhs);
            out << indent(lvl) << "auto " << e->lhs
                << " = " << e->expr << ";\n";
        }
    }
    void genLogicBlock(std::ostringstream& out, const LogicBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @logic ---\n";
        for (const auto& stmt : b.statements) {
            genLogicStmt(out, *stmt, lvl);
        }
    }

    void genLogicStmt(std::ostringstream& out, const ASTNode& node, int lvl) {
        const std::string& k = node.kind();

        if (k == "Print") {
            const auto& p = static_cast<const PrintNode&>(node);
            out << indent(lvl) << "std::cout << " << p.expr->raw << " << std::endl;\n";
        }
        else if (k == "Assign") {
            const auto& a = static_cast<const AssignNode&>(node);
            if (declaredVars.find(a.varName) == declaredVars.end()) {
                out << indent(lvl) << "auto " << a.varName << " = " << a.value->raw << ";\n";
                declaredVars.insert(a.varName);
            } else {
                out << indent(lvl) << a.varName << " = " << a.value->raw << ";\n";
            }
        }
        else if (k == "If") {
            const auto& ifn = static_cast<const IfNode&>(node);
            out << indent(lvl) << "if (" << ifn.condition->raw << ") {\n";
            for (const auto& s : ifn.thenBody) genLogicStmt(out, *s, lvl+1);
            out << indent(lvl) << "}";
            if (!ifn.elseBody.empty()) {
                out << " else {\n";
                for (const auto& s : ifn.elseBody) genLogicStmt(out, *s, lvl+1);
                out << indent(lvl) << "}";
            }
            out << "\n";
        }
        else if (k == "While") {
            const auto& wn = static_cast<const WhileNode&>(node);
            out << indent(lvl) << "while (" << wn.condition->raw << ") {\n";
            for (const auto& s : wn.body) genLogicStmt(out, *s, lvl+1);
            out << indent(lvl) << "}\n";
        }
        else if (k == "Repeat") {
            const auto& rn = static_cast<const RepeatNode&>(node);
            out << indent(lvl) << "for (int _i = 0; _i < " << rn.times << "; _i++) {\n";
            for (const auto& s : rn.body) genLogicStmt(out, *s, lvl+1);
            out << indent(lvl) << "}\n";
        }
        else {
            throw std::runtime_error("Unknown logic statement: " + k);
        }
    }

    void genOutBlock(std::ostringstream& out, const OutBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @out ---\n";
        for (const auto& line : b.lines) {
            std::string tmpl = line->tmpl;
            std::vector<std::pair<bool,std::string>> parts;
            std::string seg;
            for (int i = 0; i < (int)tmpl.size(); ) {
                if (tmpl[i] == '{') {
                    if (!seg.empty()) { parts.push_back({false, seg}); seg.clear(); }
                    int j = i + 1;
                    while (j < (int)tmpl.size() && tmpl[j] != '}') j++;
                    parts.push_back({true, tmpl.substr(i+1, j-i-1)});
                    i = j + 1;
                } else {
                    seg += tmpl[i++];
                }
            }
            if (!seg.empty()) parts.push_back({false, seg});
            out << indent(lvl) << "std::cout";
            for (const auto& p : parts) {
                if (p.first) out << " << " << p.second;
                else         out << " << \"" << escapeStr(p.second) << "\"";
            }
            if (parts.empty()) out << " << \"\"";
            out << " << std::endl;\n";
        }
    }

    std::string escapeStr(const std::string& s) {
        std::string r;
        for (char c : s) {
            if (c == '"')  r += "\\\"";
            else if (c == '\\') r += "\\\\";
            else r += c;
        }
        return r;
    }

    void genFlowBlock(std::ostringstream& out, const FlowBlockNode& b, int lvl) {
        out << "\n" << indent(lvl) << "// --- @flow ---\n";
        out << indent(lvl) << "// Flow diagram:\n";
        for (const auto& s : b.steps) {
            out << indent(lvl) << "//   " << s->from << " -> " << s->to;
            if (!s->condition.empty()) out << "  (if " << s->condition << ")";
            out << "\n";
        }
        out << indent(lvl) << "// (Flow execution represented as labeled blocks)\n";

        std::vector<std::string> labels;
        std::map<std::string, std::vector<const FlowStepNode*>> byFrom;
        for (const auto& s : b.steps) {
            if (byFrom.find(s->from) == byFrom.end())
                labels.push_back(s->from);
            byFrom[s->from].push_back(s.get());
        }

        std::set<std::string> allLabels;
        for (const auto& s : b.steps) { allLabels.insert(s->from); allLabels.insert(s->to); }

        out << indent(lvl) << "goto flow_" << b.entry << ";\n";
        for (const auto& lbl : labels) {
            out << indent(lvl) << "flow_" << lbl << ":\n";
            const auto& steps = byFrom[lbl];
            if (steps.size() == 1 && steps[0]->condition.empty()) {
                out << indent(lvl+1) << "goto flow_" << steps[0]->to << ";\n";
            } else {
                for (const auto* step : steps) {
                    if (!step->condition.empty()) {
                        out << indent(lvl+1) << "if (" << step->condition << ") "
                            << "goto flow_" << step->to << ";\n";
                    } else {
                        out << indent(lvl+1) << "goto flow_" << step->to << ";\n";
                    }
                }
            }
        }
        for (const auto& lbl : allLabels) {
            if (byFrom.find(lbl) == byFrom.end()) {
                out << indent(lvl) << "flow_" << lbl << ": ;\n";
            }
        }
    }
};
